# Workflow managed by https://github.com/AnchorFree/workflows/
name: Hadolint Linter
on: [pull_request]
jobs:
  hadolint:
    name: Hadolint scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Scanning the dockerfile
        uses: reviewdog/action-hadolint@15df5a025251f3b06814d53ba1e782f5a42b2874 # v1.44.0
        with:
          reporter: github-pr-review
          filter_mode: file
