name: Hadolint Linter
on: [pull_request]
jobs:
  hadolint:
    uses: AnchorFree/secops-workflows/.github/workflows/reusable-hadolint.yml@main
    permissions:
      contents: read
      pull-requests: write
