name: Secops Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  firewall-review:
    uses: AnchorFree/secops-workflows/.github/workflows/reusable-firewall-review.yml@main
    permissions:
      contents: read
      actions: read
      id-token: write 
