name: Trivy Scan
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
jobs:
  trivy-license-scan:
    uses: AnchorFree/secops-workflows/.github/workflows/reusable-license-check.yml@main
    permissions:
      contents: read
      actions: read
      id-token: write
      security-events: write
  trivy-config-scan:
    uses: AnchorFree/secops-workflows/.github/workflows/reusable-trivy-config.yml@main
    permissions:
      contents: read
      actions: read
      id-token: write
      security-events: write
  trivy-repo-scan:
    uses: AnchorFree/secops-workflows/.github/workflows/reusable-trivy-repo.yml@main
    permissions:
      contents: read
      actions: read
      id-token: write
      security-events: write
